# Generated by Django 5.0.7 on 2024-07-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
