# Generated by Django 5.0.7 on 2024-07-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="name",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
