# Generated by Django 5.0.7 on 2024-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_products_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="color_code",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
