# Generated by Django 5.0.7 on 2024-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_color_color_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="descriptions",
            field=models.TextField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name="products",
            name="dimension",
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name="products",
            name="weight",
            field=models.BigIntegerField(blank=True, default=1),
        ),
    ]
