# Generated by Django 5.0.7 on 2024-07-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_products_descriptions_products_dimension_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="dimension",
        ),
        migrations.AddField(
            model_name="products",
            name="depth",
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AddField(
            model_name="products",
            name="height",
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AddField(
            model_name="products",
            name="width",
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="products",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1.1, max_digits=5
            ),
        ),
    ]
