# Generated by Django 5.0.7 on 2024-07-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_remove_products_dimension_products_depth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="instock",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
