# Generated by Django 5.0.7 on 2024-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_products_instock"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="materials",
            field=models.CharField(default="Wood", max_length=50),
        ),
        migrations.AlterField(
            model_name="products",
            name="descriptions",
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name="products",
            name="instock",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
        ),
    ]
