# Generated by Django 5.0.7 on 2024-07-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_products_materials_alter_products_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name:')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail:')),
                ('content', models.TextField(verbose_name='Content:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
