# Generated by Django 5.0.7 on 2024-08-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_userordersummary_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material",
                        to="home.products",
                    ),
                ),
            ],
        ),
    ]
