# Generated by Django 5.0.7 on 2024-07-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="home.products",
            ),
            preserve_default=False,
        ),
    ]
