# Generated by Django 5.0.7 on 2024-08-23 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_productmaterials_product_products_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="materials",
        ),
    ]
