# Generated by Django 5.0.7 on 2024-07-22 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_comment_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="comment_content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="email",
            new_name="comment_email",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="name",
            new_name="comment_name",
        ),
    ]
