# Generated by Django 5.0.7 on 2024-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_remove_products_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="material",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="home.productmaterials"
            ),
        ),
    ]
