# Generated by Django 5.0.7 on 2024-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_mywishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mywishlist",
            name="product",
        ),
        migrations.AddField(
            model_name="mywishlist",
            name="products",
            field=models.ManyToManyField(related_name="wishlist", to="home.products"),
        ),
    ]
