# Generated by Django 5.0.7 on 2024-08-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_remove_products_image_productimage_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_image_product",
                to="home.productimage",
            ),
        ),
    ]
