# Generated by Django 5.0.7 on 2024-08-01 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_products_main_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="images",
        ),
    ]
