# Generated by Django 5.0.7 on 2024-08-02 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_products_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="average_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
