# Generated by Django 5.0.7 on 2024-08-02 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_products_average_rating_alter_comment_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="average_rating",
        ),
    ]
