# Generated by Django 5.0.7 on 2024-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_alter_comment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
