# Generated by Django 5.0.7 on 2024-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_usernotifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotifications",
            name="method",
            field=models.CharField(
                choices=[
                    ("PS", "Password"),
                    ("IMG", "ProfilImage"),
                    ("OP", "Order Placed"),
                    ("OD", "Order Delivered"),
                    ("NM", "Name"),
                    ("SN", "Surname"),
                    ("EM", "Email"),
                    ("ADR", "Address"),
                    ("PH", "Phone"),
                ],
                max_length=3,
            ),
        ),
    ]
