# Generated by Django 5.0.7 on 2024-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilpicture",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/media/profil_picture/unnamed.jpg",
                upload_to="profil_picture",
            ),
        ),
    ]
