# Generated by Django 5.0.7 on 2024-09-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_profilpicture_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilpicture",
            name="address",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="profilpicture",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
