# Generated by Django 5.0.7 on 2024-09-15 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profilpicture_address_profilpicture_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilpicture",
            old_name="address",
            new_name="user_address",
        ),
    ]
